# Generated by Django 5.1.4 on 2026-04-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyaka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client info')),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'indexes': [models.Index(fields=['username', '-timestamp'], name='shyaka_logi_usernam_05cb43_idx'), models.Index(fields=['ip_address', '-timestamp'], name='shyaka_logi_ip_addr_6176da_idx'), models.Index(fields=['-timestamp'], name='shyaka_logi_timesta_9641eb_idx')],
            },
        ),
    ]
