# Generated by Django 5.1.4 on 2026-04-17 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyaka', '0003_alter_loginattempt_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('registration', 'User Registration'), ('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('role_assigned', 'Role Assigned'), ('role_removed', 'Role Removed'), ('profile_updated', 'Profile Updated')], db_index=True, help_text='Type of security-relevant event', max_length=20)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address from which the event originated')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information')),
                ('description', models.TextField(help_text='Human-readable description of the event')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured event details (never includes secrets)')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (for privilege changes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_actor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who was affected by the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='shyaka_audi_timesta_140191_idx'), models.Index(fields=['event_type', '-timestamp'], name='shyaka_audi_event_t_c4f158_idx'), models.Index(fields=['user', '-timestamp'], name='shyaka_audi_user_id_0df2ed_idx'), models.Index(fields=['actor', '-timestamp'], name='shyaka_audi_actor_i_8f60b0_idx'), models.Index(fields=['ip_address', '-timestamp'], name='shyaka_audi_ip_addr_a2afef_idx')],
            },
        ),
    ]
