# Generated by Django 5.1.4 on 2026-04-20 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyaka', '0004_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title/name', max_length=255)),
                ('file', models.FileField(help_text='Uploaded document file', upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, help_text='Original filename (for display)', max_length=255)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of uploaded file', max_length=100)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='If True, any authenticated user can view')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag (document not actually deleted)')),
                ('owner', models.ForeignKey(help_text='User who uploaded this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['owner', '-uploaded_at'], name='shyaka_docu_owner_i_748999_idx'), models.Index(fields=['uploaded_at'], name='shyaka_docu_uploade_5d2b50_idx')],
            },
        ),
    ]
