"""
Django settings for devsec_demo project.

Generated by 'django-admin startproject' using Django 6.0.4.

Production-hardened security configuration with comprehensive
security controls for deployment.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

Django Deployment Checklist:
https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================================
# SECURITY: SECRET KEY MANAGEMENT
# ============================================================================
# CRITICAL: Never commit secrets to version control. Use environment variables.

def get_secret(var_name, default=None, required=False):
    """
    Safely retrieve environment variables with validation.
    
    Args:
        var_name: Name of environment variable
        default: Default value if not set
        required: If True, raise error if variable not set
    
    Returns:
        Environment variable value or default
    
    Raises:
        RuntimeError: If required variable not set
    """
    value = os.environ.get(var_name, default)
    
    if required and value is None:
        raise RuntimeError(
            f"Required environment variable {var_name} is not set. "
            f"Set it before starting the application."
        )
    
    return value


# Secret key MUST be set in production - never use hardcoded defaults
SECRET_KEY = get_secret('DJANGO_SECRET_KEY', required=False)

if not SECRET_KEY:
    # Development fallback only - NEVER use in production
    if os.environ.get('ENVIRONMENT') == 'production':
        raise RuntimeError(
            "CRITICAL: DJANGO_SECRET_KEY environment variable must be set in production. "
            "Generate a new key using: python manage.py shell -c "
            "'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
        )
    # Development only
    SECRET_KEY = 'dev-key-only-for-development-not-for-production'


# ============================================================================
# SECURITY: DEBUG MODE
# ============================================================================
# DEBUG must be False in production - never expose debug information to attackers

_debug_str = os.environ.get('DJANGO_DEBUG', 'false').lower()
DEBUG = _debug_str in ('true', '1', 'yes', 'on')

if DEBUG and os.environ.get('ENVIRONMENT') == 'production':
    raise RuntimeError(
        "CRITICAL: DEBUG is enabled in production mode! "
        "Set DJANGO_DEBUG=false and ENVIRONMENT=production to disable."
    )

# In production, Django will show generic error pages instead of debug information
ENVIRONMENT = get_secret('ENVIRONMENT', 'development')


# ============================================================================
# SECURITY: ALLOWED HOSTS
# ============================================================================
# Prevent Host Header attacks by validating incoming Host headers

_allowed_hosts = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts.split(',')]

# In production, explicitly set ALLOWED_HOSTS to your domain(s):
# ALLOWED_HOSTS=['example.com', 'www.example.com']
if ENVIRONMENT == 'production' and ALLOWED_HOSTS == ['localhost', '127.0.0.1']:
    raise RuntimeError(
        "CRITICAL: ALLOWED_HOSTS not configured for production. "
        "Set ALLOWED_HOSTS environment variable with your domain(s)."
    )


# ============================================================================
# SECURITY: HTTPS / SSL / SECURE TRANSPORT
# ============================================================================
# Force HTTPS in production to prevent man-in-the-middle attacks

if ENVIRONMENT == 'production':
    # Redirect all HTTP to HTTPS
    SECURE_SSL_REDIRECT = True
    
    # Set SECURE flag on cookies (only send over HTTPS)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Enable HSTS (HTTP Strict-Transport-Security)
    # Tells browsers to always use HTTPS for this domain
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Development: Allow HTTP (easier for local testing)
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# ============================================================================
# SECURITY: COOKIE SECURITY SETTINGS
# ============================================================================
# Protect session and CSRF cookies from theft and tampering

# Set HttpOnly flag to prevent JavaScript access to cookies
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# SameSite policy prevents CSRF attacks
# 'Strict' is most secure but breaks some legitimate use cases
# 'Lax' is a good balance (Django default)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Session configuration
SESSION_COOKIE_AGE = 1209600  # 2 weeks (default)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = False  # Reduce database writes

# CSRF configuration
CSRF_COOKIE_AGE = 31449600  # 1 year (default)
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []


# ============================================================================
# SECURITY: CONTENT SECURITY
# ============================================================================
# Protect against clickjacking, content sniffing, and other attacks

# Prevent clickjacking attacks (Django default: 'DENY')
X_FRAME_OPTIONS = 'DENY'

# Prevent content type sniffing
SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': ("'self'",),
    'script-src': ("'self'", "'unsafe-inline'"),  # TODO: Remove unsafe-inline in production
    'style-src': ("'self'", "'unsafe-inline'"),   # TODO: Remove unsafe-inline in production
    'img-src': ("'self'", 'data:', 'https:'),
    'font-src': ("'self'",),
    'connect-src': ("'self'",),
    'frame-ancestors': ("'none'",),
}


# ============================================================================
# SECURITY: ADDITIONAL SECURITY HEADERS
# ============================================================================

# Content Security Policy header settings
SECURE_PROXY_SSL_HEADER = None  # Set if behind proxy: ('HTTP_X_FORWARDED_PROTO', 'https')

# Additional security headers
# Prevent MIME type sniffing
SECURE_BROWSER_XSS_FILTER = True

# Referrer-Policy header
SECURE_REFERRER_POLICY = 'same-origin'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shyaka',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Add security headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devsec_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'devsec_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # In production, use PostgreSQL:
        # 'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': get_secret('DATABASE_NAME', required=True),
        # 'USER': get_secret('DATABASE_USER', required=True),
        # 'PASSWORD': get_secret('DATABASE_PASSWORD', required=True),
        # 'HOST': get_secret('DATABASE_HOST', required=True),
        # 'PORT': get_secret('DATABASE_PORT', '5432'),
    }
}


# ============================================================================
# SECURITY: PASSWORD VALIDATION
# ============================================================================
# Enforce strong password requirements for all users

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        # Prevents passwords too similar to username/email
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Enforce minimum 12 character passwords
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        # Prevents use of common weak passwords
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        # Prevents all-numeric passwords
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ============================================================================
# SECURITY: STATIC FILES CONFIGURATION
# ============================================================================
# Static files (CSS, JavaScript, images) for deployment

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Where collectstatic puts files

# Optimize static file serving
if ENVIRONMENT == 'production':
    # Enable static file caching
    STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================
# For development, use the console backend to print emails to console
# In production, configure SMTP or use a service like SendGrid, Mailgun, etc.

if DEBUG:
    # Development: Print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production: Configure your email backend here
    # Example: SMTP backend
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = get_secret('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(get_secret('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = get_secret('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_HOST_USER = get_secret('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = get_secret('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = get_secret('DEFAULT_FROM_EMAIL', 'noreply@shyaka.local')


# ============================================================================
# PASSWORD RESET CONFIGURATION
# ============================================================================
# Security-critical settings for password reset functionality

# Token expiration time in seconds (default: 1209600 = 2 weeks)
# This should be SHORT enough for security but LONG enough for users to use
PASSWORD_RESET_TIMEOUT = int(get_secret('PASSWORD_RESET_TIMEOUT', '3600'))  # 1 hour

# Default key lifetime in seconds for password reset tokens
# Django's PasswordResetTokenGenerator uses this to validate tokens
# The token includes a hash of the user's password, so changing the password invalidates old tokens


# ============================================================================
# Media Files (User Uploads) Configuration
# ============================================================================
# Security configuration for file uploads (avatars, documents, etc.)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Ensure directory exists
MEDIA_ROOT.mkdir(exist_ok=True)


# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
# Log security-relevant events for monitoring and compliance

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
(BASE_DIR / 'logs').mkdir(exist_ok=True)
